# Generated by Django 3.1 on 2020-09-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='users/default.png', upload_to='users/%Y/%m/%d/'),
        ),
    ]
